### ISSUE TITLE
Magmatic smeltery crash

### ISSUE THREAD

**Issue by TheMadmanofChaos** [Modbder/EssentialCraft3#11]
Essential craft: 4.6.1710.32
Dummy core: 1.13

I was attempting to automate the Magmatic smeltery using a blood magic "Orchestra of the Phantom hands". After telling the ritual to output lava buckets into the side of the smeltery, this crash occurred

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/9/15 4:43 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 3
    at ec3.common.tile.TileMRUGeneric.func_94128_d(TileMRUGeneric.java:260)
    at WayofTime.alchemicalWizardry.common.spell.complex.effect.SpellHelper.insertStackIntoInventory(SpellHelper.java:545)
    at WayofTime.alchemicalWizardry.common.rituals.RitualEffectItemRouting.performEffect(RitualEffectItemRouting.java:174)
    at WayofTime.alchemicalWizardry.api.rituals.Rituals.performEffect(Rituals.java:260)
    at WayofTime.alchemicalWizardry.common.tileEntity.TEMasterStone.performRitual(TEMasterStone.java:379)
    at WayofTime.alchemicalWizardry.common.tileEntity.TEMasterStone.func_145845_h(TEMasterStone.java:374)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at ec3.common.tile.TileMRUGeneric.func_94128_d(TileMRUGeneric.java:260)
    at WayofTime.alchemicalWizardry.common.spell.complex.effect.SpellHelper.insertStackIntoInventory(SpellHelper.java:545)
    at WayofTime.alchemicalWizardry.common.rituals.RitualEffectItemRouting.performEffect(RitualEffectItemRouting.java:174)
    at WayofTime.alchemicalWizardry.api.rituals.Rituals.performEffect(Rituals.java:260)
    at WayofTime.alchemicalWizardry.common.tileEntity.TEMasterStone.performRitual(TEMasterStone.java:379)
    at WayofTime.alchemicalWizardry.common.tileEntity.TEMasterStone.func_145845_h(TEMasterStone.java:374)

-- Block entity being ticked --
Details:
    Name: containerMasterStone // WayofTime.alchemicalWizardry.common.tileEntity.TEMasterStone
    Block type: ID #557 (tile.blockMasterStone // WayofTime.alchemicalWizardry.common.block.BlockMasterStone)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (678,7,-551), Chunk: (at 6,0,9 in 42,-35; contains blocks 672,0,-560 to 687,255,-545), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
    Actual block type: ID #557 (tile.blockMasterStone // WayofTime.alchemicalWizardry.common.block.BlockMasterStone)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: A true Madman
    All players: 1 total; [EntityPlayerMP['TheMadman'/3226544, l='A true Madman', x=679.07, y=4.00, z=-549.46]]
    Chunk stats: ServerChunkCache: 966 Drop: 0
    Level seed: -1803903097
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-14,64,25), Chunk: (at 2,4,9 in -1,1; contains blocks -16,0,16 to -1,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 15265715 game time, 16754160 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 39177 (now: false), thunder time: 3547 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_31, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 355984184 bytes (339 MB) / 1014456320 bytes (967 MB) up to 2079719424 bytes (1983 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2000m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:PermSize=256m -XX:MaxPermSize=512m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1428 34 mods loaded, 34 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.3.1428-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forge{10.13.3.1428} [Minecraft Forge](forge-1.7.10-10.13.3.1428-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CodeChickenCore{1.0.4.35} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NotEnoughItems{1.0.4.95} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.95-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    WitchingGadgetsCore{1.1.8} [Witching Gadgets Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    abyssalcraft{1.8.7} [AbyssalCraft](AbyssalCraft-1.7.10-1.8.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Waila{1.5.8} [Waila](Waila-1.5.8a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Automagy{0.26} [Automagy](Automagy-1.7.10-0.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    AWWayofTime{v1.3.2} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.2aBeta-16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    buffedtools{1.1.1710.1} [Buffed Tools](BuffedTools-1.1.1710.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    difficultlife{1.1.1710.11} [Difficult Life](DifficultLife-1.2.1710.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    DummyCore{1.13} [DummyCore](DummyCore1.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    essentialcraft{4.6.1710.32} [Essential Craft 3](EssentialCraftv4.6.1710.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    essenthaum{1.1.1710.0} [Essential Thaumaturgy](EssentialThaumaturgy-1.1.1710.11EC%284.4.1710.37%29TC%284.2.3.5%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FastCraft{1.9} [FastCraft](fastcraft-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-503.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ForbiddenMagic{1.7.10-0.57} [Forbidden Magic](Forbidden Magic-1.7.10-0.57.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    guideapi{1.7.10-1.0.0-16} [Guide-API](Guide-API-1.7.10-1.0.0-16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    xreliquary{1.2} [Reliquary](Reliquary-1.2.257.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TaintedMagic{1.1.5.4} [Tainted Magic](TaintedMagic-1.1.5.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    terraarts{1.0.1710.1} [Terra Arts](TerraArts-1.1.1710.27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    thaumicbases{1.0.1710.8} [Thaumic Bases](ThaumicBases1.0.1710.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ThaumicHorizons{1.1.5} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    thaumicinfusion{4.002} [Thaumic Infusion](ThaumicInfusion-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TravellersGear{1.16.4} [Traveller's Gear](TravellersGear-1.7.10-1.16.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    WitchingGadgets{1.1.8} [Witching Gadgets](WitchingGadgets-1.7.10-1.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['TheMadman'/3226544, l='A true Madman', x=679.07, y=4.00, z=-549.46]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'.

**Comment by TheMadmanofChaos** [comment]
The latest build fixed this issue. Closing report.
