### ISSUE TITLE
Incompatibility with Hardcore Ender Expansion

### ISSUE THREAD

**Issue by learntechguy** [Modbder/EssentialCraft3#18]
Using the Spawner collector on the Monster Spawners in The end will crash the client. (FTB Horizons II)

The crash report error says the following:

Unexpected error

java.lang.ClassCastException: chylex.hee.tileentity.TileEntityCustomSpawner cannot be cast to net.minecraft.tileentity.TileEntityMobSpawner
    at ec3.common.item.ItemSpawnerCollector.onItemUseFirst(ItemSpawnerCollector.java:32)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:317)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Modbder** [comment]
Is more of a HEE issue, but I can easily fix that.
