### ISSUE TITLE
Ticking block entity

### ISSUE THREAD

**Issue by EnderNyktos** [Modbder/EssentialCraft3#48]
> ---- Minecraft Crash Report ----
> // I'm sorry, Dave.
> 
> Time: 24/08/16 09:45 AM
> Description: Ticking block entity
> 
> java.lang.NullPointerException: Ticking block entity
>   at ec3.common.tile.TileMagicalChest.func_70302_i_(TileMagicalChest.java:58)
>   at ec3.common.tile.TileMagicalChest.func_145841_b(TileMagicalChest.java:274)
>   at DummyCore.Utils.TileStatTracker.tileNeedsSyncing(TileStatTracker.java:23)
>   at ec3.common.tile.TileMagicalChest.func_145845_h(TileMagicalChest.java:173)
>   at net.minecraft.world.World.func_72939_s(World.java:1939)
>   at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
>   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
>   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
>   at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
>   at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- Head --
> Stacktrace:
>   at ec3.common.tile.TileMagicalChest.func_70302_i_(TileMagicalChest.java:58)
>   at ec3.common.tile.TileMagicalChest.func_145841_b(TileMagicalChest.java:274)
>   at DummyCore.Utils.TileStatTracker.tileNeedsSyncing(TileStatTracker.java:23)
>   at ec3.common.tile.TileMagicalChest.func_145845_h(TileMagicalChest.java:173)
>   at net.minecraft.world.World.func_72939_s(World.java:1939)
> 
> -- Block entity being ticked --
> Details:
>   Name: ec3:ec3.common.tile.TileMagicalChest // ec3.common.tile.TileMagicalChest
>   Block type: ID #1262 (tile.essentialcraft.chest // ec3.common.block.BlockEC3Chest)
>   Block data value: 15 / 0xF / 0b1111
>   Block location: World: (-316,82,603), Chunk: (at 4,5,11 in -20,37; contains blocks -320,0,592 to -305,255,607), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
>   Actual block type: ID #1262 (tile.essentialcraft.chest // ec3.common.block.BlockEC3Chest)
>   Actual block data value: 15 / 0xF / 0b1111
> Stacktrace:
>   at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
>   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
> 
> -- Affected level --
> Details:
>   Level name: ShadowLand
>   All players: 1 total; [EntityPlayerMP['ShAdOwDaRkSoUl'/7603, l='ShadowLand', x=-316,30, y=82,00, z=605,09]]
>   Chunk stats: ServerChunkCache: 595 Drop: 0
>   Level seed: 4375895917946165507
>   Level generator: ID 05 - BIOMESOP, ver 0. Features enabled: true
>   Level generator options: 
>   Level spawn location: World: (-566,64,965), Chunk: (at 10,4,5 in -36,60; contains blocks -576,0,960 to -561,255,975), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
>   Level time: 7859924 game time, 8426309 day time
>   Level dimension: 0
>   Level storage version: 0x04ABD - Anvil
>   Level weather: Rain time: 10848 (now: true), thunder time: 60762 (now: false)
>   Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> Stacktrace:
>   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
>   at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
>   at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> 
> -- System Details --
> Details:
>   Minecraft Version: 1.7.10
>   Operating System: Windows 7 (amd64) version 6.1
>   Java Version: 1.8.0_101, Oracle Corporation
>   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>   Memory: 415848624 bytes (396 MB) / 1378877440 bytes (1315 MB) up to 1908932608 bytes (1820 MB)
>   JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
>   AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>   IntCache: cache: 36, tcache: 0, allocated: 13, tallocated: 96
>   FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 104 mods loaded, 104 mods active
>   States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>   UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
>   UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
>   UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
>   UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
>   UCHIJAAAA   MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) 
>   UCHIJAAAA   NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
>   UCHIJAAAA   FastCraft{1.23} [FastCraft](fastcraft-1.23.jar) 
>   UCHIJAAAA   battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
>   UCHIJAAAA   movillages{1.4.2} [Mo' Villages]([1.7.10]MoVillages-1.4.2.jar) 
>   UCHIJAAAA   bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
>   UCHIJAAAA   Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) 
>   UCHIJAAAA   abyssalcraft{1.9.1.3} [AbyssalCraft](AbyssalCraft-1.7.10-1.9.1.3-FINAL.jar) 
>   UCHIJAAAA   Railcraft{9.12.2.0} [Railcraft](Railcraft_1.7.10-9.12.2.0.jar) 
>   UCHIJAAAA   chisel{2.9.5.11} [Chisel](Chisel-2.9.5.11.jar) 
>   UCHIJAAAA   koresample{1.7.10-1.3.2} [Kore Sample](KoreSample-1.7.10-1.3.2.jar) 
>   UCHIJAAAA   dendrology{1.7.10-1.6.4} [Ancient Trees](AncientTrees-1.7.10-1.6.4.jar) 
>   UCHIJAAAA   Aquaculture{1.2.6} [Aquaculture](Aquaculture-1.7.10-1.2.6.21.jar) 
>   UCHIJAAAA   smeltchevsky{b3} [Armor Smelter](ArmorSmelter_1.7.10_b3.zip) 
>   UCHIJAAAA   ATG{0.10.0} [Alternate Terrain Generation](ATG-1.7.10-0.12.0.jar) 
>   UCHIJAAAA   Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) 
>   UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
>   UCHIJAAAA   betterbreeds{0.2b} [Better Breeds](BB [0.2b].jar) 
>   UCHIJAAAA   BiblioCraft{1.11.5} [BiblioCraft](BiblioCraft[v1.11.5][MC1.7.10].jar) 
>   UCHIJAAAA   BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.2027-universal.jar) 
>   UCHIJAAAA   BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) 
>   UCHIJAAAA   boilerplate{6.3.0.81} [Boilerplate](boilerplate-1.7.10-6.3.0.81-universal.jar) 
>   UCHIJAAAA   CartLivery{0.11.1} [Cart Livery](CartLivery-1.7.10-0.11.1.jar) 
>   UCHIJAAAA   cfm{3.4.8} [§9MrCrayfish's Furniture Mod](cfm-3.4.8-mc1.7.10.jar) 
>   UCHIJAAAA   Ztones{1.7.10} [Ztones](Ztones-1.7.10-2.2.1.jar) 
>   UCHIJAAAA   chiseltones{@VERSION@} [Chisel Tones](ChiselTones-1.7.10-1.0-3.jar) 
>   UCHIJAAAA   chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar) 
>   UCHIJAAAA   ColouredTorches{1.7.10-1.1} [Coloured Torches](ColouredTorches-1.7.10-1.2.1.jar) 
>   UCHIJAAAA   cookingbook{1.0.140} [Cooking for Blockheads](cookingbook-mc1.7.10-1.0.140.jar) 
>   UCHIJAAAA   CraftHeraldry{1.1.3} [CraftHeraldry](CraftHeraldry 1.1.3.jar) 
>   UCHIJAAAA   custom_sword{1.7.10} [Custom Sword  By Kelco_K22](custom_sword_1.7.10_V0.14.jar) 
>   UCHIJAAAA   CustomSpawner{3.3.0} [DrZhark's CustomSpawner](CustomMobSpawner 3.3.0.zip) 
>   UCHIJAAAA   DamageIndicatorsMod{3.2.0} [Damage Indicators](Damage-Indicators-Mod-1.7.10.jar) 
>   UCHIJAAAA   doggystyle{1.1.3.99} [Doggy Style](DoggyStyle-1.1.3.99.jar) 
>   UCHIJAAAA   druidry{2016.8.10-1.7.10} [§2Druidry](druidry%282016.8.10.2%29%281.7.10%29.jar) 
>   UCHIJAAAA   MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.3.1.zip) 
>   UCHIJAAAA   DummyCore{1.13} [DummyCore](DummyCore1.13.jar) 
>   UCHIJAAAA   DynamicLights{1.3.9} [Dynamic Lights](DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module](DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module](DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light](DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module](DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
>   UCHIJAAAA   Enchiridion{1.3} [Enchiridion](Enchiridion 2-1.7.10-2.0.2a.jar) 
>   UCHIJAAAA   Enchiridion2{2.0.2a} [Enchiridion 2](Enchiridion 2-1.7.10-2.0.2a.jar) 
>   UCHIJAAAA   endercompass{1.2} [Ender Compass](EnderCompass-1.7.10-1.2.jar) 
>   UCHIJAAAA   endercore{1.7.10-0.2.0.36_beta} [EnderCore](EnderCore-1.7.10-0.2.0.36_beta.jar) 
>   UCHIJAAAA   endercrop{1.7.10-1.1} [Ender Crop](endercrop-1.7.10-1.2.jar) 
>   UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
>   UCHIJAAAA   EnderIO{1.7.10-2.3.0.429_beta} [Ender IO](EnderIO-1.7.10-2.3.0.429_beta.jar) 
>   UCHIJAAAA   enderioaddons{0.10.11} [Ender IO Addons](EnderIOAddons-1.7.10-2.3.0.427_beta-0.10.11.54_beta.jar) 
>   UCHIJAAAA   enderutilities{0.5.3} [Ender Utilities](enderutilities-1.7.10-0.5.3.jar) 
>   UCHIJAAAA   essentialcraft{4.6.1710.63} [Essential Craft 3](EssentialCraftv4.6.1710.63.jar) 
>   UCHIJAAAA   golems{1.20} [Extra Golems](Extra-Golems[1.7.10]-1.20.jar) 
>   UCHIJAAAA   extrabuttons{1.7.10.1} [ExtraButtons](ExtraButtons-1.7.10.1.jar) 
>   UCHIJAAAA   GardenContainers{1.7.10-1.7.0} [Garden Containers](GardenStuff-1.7.10-1.7.0.jar) 
>   UCHIJAAAA   GardenCore{1.7.10-1.7.0} [Garden Core](GardenStuff-1.7.10-1.7.0.jar) 
>   UCHIJAAAA   GardenStuff{1.7.10-1.7.0} [Garden Stuff](GardenStuff-1.7.10-1.7.0.jar) 
>   UCHIJAAAA   GardenTrees{1.7.10-1.7.0} [Garden Trees](GardenStuff-1.7.10-1.7.0.jar) 
>   UCHIJAAAA   GraveStone{2.16.1} [GraveStone](GraveStone-2.16.1.jar) 
>   UCHIJAAAA   Growthcraft{1.7.10-2.6.3} [Growthcraft](growthcraft-1.7.10-2.6.3-complete.jar) 
>   UCHIJAAAA   Growthcraft|Cellar{1.7.10-2.6.3} [Growthcraft Cellar](growthcraft-1.7.10-2.6.3-complete.jar) 
>   UCHIJAAAA   Growthcraft|Apples{1.7.10-2.6.3} [Growthcraft Apples](growthcraft-1.7.10-2.6.3-complete.jar) 
>   UCHIJAAAA   Growthcraft|Bamboo{1.7.10-2.6.3} [Growthcraft Bamboo](growthcraft-1.7.10-2.6.3-complete.jar) 
>   UCHIJAAAA   Growthcraft|Bees{1.7.10-2.6.3} [Growthcraft Bees](growthcraft-1.7.10-2.6.3-complete.jar) 
>   UCHIJAAAA   Growthcraft|Fishtrap{1.7.10-2.6.3} [Growthcraft Fishtrap](growthcraft-1.7.10-2.6.3-complete.jar) 
>   UCHIJAAAA   Growthcraft|Grapes{1.7.10-2.6.3} [Growthcraft Grapes](growthcraft-1.7.10-2.6.3-complete.jar) 
>   UCHIJAAAA   Growthcraft|Hops{1.7.10-2.6.3} [Growthcraft Hops](growthcraft-1.7.10-2.6.3-complete.jar) 
>   UCHIJAAAA   Growthcraft|Milk{1.7.10-2.6.3} [Growthcraft Milk](growthcraft-1.7.10-2.6.3-complete.jar) 
>   UCHIJAAAA   Growthcraft|Rice{1.7.10-2.6.3} [Growthcraft Rice](growthcraft-1.7.10-2.6.3-complete.jar) 
>   UCHIJAAAA   hammertime{Hammer Time-1.7.10-1.3.6} [Hammer Time!](HammerTime-1.3.6.jar) 
>   UCHIJAAAA   HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.8.6.jar) 
>   UCHIJAAAA   iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
>   UCHIJAAAA   Hats{4.0.1} [Hats](Hats-4.0.1.jar) 
>   UCHIJAAAA   HatStand{4.0.0} [HatStand](HatStand-4.0.0.jar) 
>   UCHIJAAAA   TIcarus{@VERSION@} [Icarus](Icarus-1.0.6-hotfix.jar) 
>   UCHIJAAAA   levels{r3.0.1} [Levels](Levels-1.7.10-r3.0.1.jar) 
>   UCHIJAAAA   malisiscore{1.7.10-0.14.3} [MalisisCore](malisiscore-1.7.10-0.14.3.jar) 
>   UCHIJAAAA   malisisdoors{1.7.10-1.13.2} [Malisis' Doors](malisisdoors-1.7.10-1.13.2.jar) 
>   UCHIJAAAA   Mariculture{1.7.10-1.3.0-4} [Mariculture](Mariculture-Deluxe-1.7.10-1.3.0-4.jar) 
>   UCHIJAAAA   MariTech{1.0} [Marine Technlogy](Mariculture-Deluxe-1.7.10-1.3.0-4.jar) 
>   UCHIJAAAA   moarcarts{1.2.3-8} [MoarCarts](moarcarts-1.7.10-1.2.3-8.jar) 
>   UCHIJAAAA   MouseTweaks{2.4.4} [Mouse Tweaks](MouseTweaks-2.4.4-mc1.7.10.jar) 
>   UCHIJAAAA   placeableitems{PreAlpha 2.0} [Placeable Items Mod](placeableitems-PreAlpha 2.0.jar) 
>   UCHIJAAAA   primitivemobs{1.0} [Primitive Mobs](primitivemobs-1.0c-1.7.10.jar) 
>   UCHIJAAAA   RadixCore{2.1.2} [RadixCore](RadixCore-1.7.10-2.1.2-universal.jar) 
>   UCHIJAAAA   RightClickTorch{1.0.2} [RightClickTorch](rightclicktorch-1.7.10-1.0.2.jar) 
>   UCHIJAAAA   roadblock{1.7.10-2.1.8-} [Roadblocks](Roadblocks-1.7.10-2.1.8.jar) 
>   UCHIJAAAA   Roguelike{1.4.4} [Roguelike Dungeons](roguelike-1.7.10-1.4.4.jar) 
>   UCHIJAAAA   AS_Ruins{15.4} [Ruins Spawning System](Ruins-1.7.10.jar) 
>   UCHIJAAAA   runicdungeons{1.1.7b} [Runic Dungeons](RunicDungeons-1.1.7b.jar) 
>   UCHIJAAAA   TravellersGear{1.16.6} [Traveller's Gear](TravellersGear-1.7.10-1.16.6.jar) 
>   UCHIJAAAA   AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) 
>   UCHIJAAAA   warpbook{2.0.null} [Warp Book](warpbook-1.7.10_2.0.37.jar) 
>   UCHIJAAAA   woodstuff{1.3.2} [WoodStuff](WoodStuff-1.3.2.jar) 
>   GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
>   Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
>   EnderIO: No known problems detected.
>   Profiler Position: N/A (disabled)
>   Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>   Player Count: 1 / 8; [EntityPlayerMP['ShAdOwDaRkSoUl'/7603, l='ShadowLand', x=-316,30, y=82,00, z=605,09]]
>   Type: Integrated Server (map_client.txt)
>   Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by EnderNyktos** [comment]
It seems to be a chisel's problem i was trying to use this chest for decoratives purposes
