### ISSUE TITLE
Player unable to log in after shift clicking a bauble in.

### ISSUE THREAD

**Issue by ProsperCraft** [Modbder/EssentialCraft3#5]
He shift clicked a doctors belt into his baubles slot, then was disconnected and could not log back in.
He was able to wear it ok without shift clicking it in.

[13:03:25 INFO]: JoshuaCarr63 is an EntityPlayerMP attempting to send the worldId packet
[13:03:25 ERROR]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingEvent$LivingUpdateEvent@441a1321:
java.lang.NoSuchMethodError: net.minecraft.potion.Potion.func_76398_f()Z
        at ec3.common.item.BaublesModifier.onWornTick(BaublesModifier.java:166) ~[BaublesModifier.class:?]
        at baubles.common.event.EventHandlerEntity.playerTick(EventHandlerEntity.java:31) ~[EventHandlerEntity.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_40_EventHandlerEntity_playerTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1448.121]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:1.7.10-1448.121]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:297) [ForgeHooks.class:1.7.10-1448.121]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1846) [sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:315) [yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:393) [mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:482) [nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(C03PacketPlayer.java:234) [jf.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]

**Comment by Modbder** [comment]
The problem is not in baubles here - it seems, like he is wearing something, like a Doctor's belt, and some mod has incorrect potion registration, and, therefore, can't be checked, if the potion is good or bad. You can fix this by removing all potion effects from him, or by removing the belt(can be done by editing ether the .dat file, which is responsible for the player itself, or by editing his baubles.dat file. .dat files can be edited by any NBT editor). However, I will fix this issue as soon as I can.

**Comment by Modbder** [comment]
Fixed, grab the fixed version in 10 minutes or so from curseforge.

**Comment by ProsperCraft** [comment]
Removing the .baub and .baubbak and .ecdat  allowed him to log in without problems.

**Comment by ProsperCraft** [comment]
Thank you for the fix, we will look forward to a Daybreaker modpack update.
